# Generated by Django 2.2.3 on 2021-10-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='proyectos')),
            ],
            options={
                'verbose_name': 'galeria',
                'verbose_name_plural': 'galerias',
            },
        ),
    ]
