# Generated by Django 2.2.3 on 2021-10-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20211019_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='producto',
        ),
    ]
